{
	"th06 BGM In-game format": "♪%s",
	"th06_ascii_centered_stage_demo": "DEMO PLAY",
	"th06_ascii_replay": "%s %8s  %8s %-7s  %-7s",
	"th06_ascii_replay_save_header": "No.   Name     Date     Player  Score",
	"th06_ascii_replay_save": "No.%.2d %8s %8s %7s %10d",
	"th06_ascii_replay_save_empty": "No.%.2d -------- --/--/-- -------          0",
	"th06_ascii_replay_stage_header": "Stage   LastScore",
	"th06_ascii_replay_stage": "%-6s %10d",
	"th06_ascii_replay_stage_empty": "%-6s  ---------",
	"th07 Stats Character Format": "<l$%s> %6d\t %6d\t %6d\t %6d\t %6d\t %6d",
	"th07 Stats Character Format +Phantasm": "<l$%s> %6d\t %6d\t %6d\t %6d\t %6d\t %6d\t %6d",
	"th08_spell_description_string_format": "Ｎｏ．%s　　%s",
	"th08_????????": "？？？？？？？？",
	"th08_?????????": "？？？？？？？？？",
	"th10 Result Known Spell": "No. <r$%3d$999>  %s <r$%4d/%4d$>",
	"th10 Result Unknown Spell": "No. <r$%3d$999>  ？？？？？？？？？？？？？？？？？？？？？ <r$%4d/%4d$>",
	"th15 Result Known Spell": "No.<r$%s%s%s$９９９> %s <r$%4d/%4d$>",
	"th15 Result Unknown Spell": "No.<r$%s%s%s$９９９> ？？？？？？？？？？？？？？？？？？？？？ <r$%4d/%4d$>",
	"Music Room Numbered Title": "No. <r$%2d$99>  %s",
	"Music Room Unknown Title": "No. <r$%2d$99>  ？？？？？？？？？？？",
	"Music Room Note Title": "<t$♪><ls$%d> %s",
	"Dialog font": "MS Shell Dlg",
	"th16_replay_user_menu_format": "%s  %s %.2d/%.2d/%.2d %.2d:%.2d %s %s%s %s %2.1f%%",
	"th17_replay_user_menu_format": "%s  %s %.2d/%.2d/%.2d %.2d:%.2d %s  %s %s %2.1f%%"
}
