{
	"title": "th09 config",
	"font": "Dialog font",
	"font_size": 8,
	"items": [
		"th08 fog",
		"th07 16bits textures",
		"th07 DirectInput",
		"th07 BGM memory",
		"th08 rasterizer mode",
		"th08 VSync",
		"th06 screen mode",
		"th07 fullscreen",
		"th06 windowed",
		"th06 colors",
		"th07 32bits mode",
		"th06 16bits mode",
		"th06 refresh rate",
		"th09 full rate",
		"th06 half rate",
		"th06 third rate",
		"th07 effect quality",
		"th07 low effects",
		"th07 medium effects",
		"th07 high effects",
		"th09 1P controller",
		"th09 gamepad 1",
		"th09 gamepad 2",
		"th09 all keyboard",
		"th09 left side keyboard",
		"th09 right side keyboard",
		"th09 2P controller",
		"th09 gamepad 1",
		"th09 gamepad 2",
		"th09 all keyboard",
		"th09 left side keyboard",
		"th09 right side keyboard",
		"th09 no save",
		"th09 save"
	]
}
