{
	"title": "th07 config",
	"font": "Dialog font",
	"font_size": 8,
	"items": [
		"th06 vertex",
		"th06 fog",
		"th07 16bits textures",
		"th07 DirectInput",
		"th07 BGM memory",
		"th06 color composition",
		"th06 depth test",
		"th06 rasterizer mode",
		"th07 draw screen",
		"th07 VSync",
		"th07 fullscreen",
		"th06 windowed",
		"th07 low effects",
		"th07 medium effects",
		"th07 high effects",
		"th06 full rate",
		"th06 half rate",
		"th06 third rate",
		"th07 32bits mode",
		"th06 16bits mode",
		"th06 accept",
		"th06 cancel",
		"th06 screen mode",
		"th07 effect quality",
		"th06 refresh rate",
		"th06 colors",
		null,
		null,
		"th06 pad X axis",
		"th06 pad Y axis",
		"th06 check pad"
	]
}
