{
	"title": "th06 config",
	"font": "Dialog font",
	"font_size": 8,
	"items": [
		"th06 vertex",
		"th06 fog",
		"th06 16bit textures",
		"th06 Gouraud shading",
		"th06 color composition",
		"th06 rasterizer mode",
		"th06 clear buffer",
		"th06 minimum graphics",
		"th06 depth test",
		"th06 force frame",
		"th06 fullscreen",
		"th06 windowed",
		"th06 full rate",
		"th06 half rate",
		"th06 third rate",
		"th06 32bits mode",
		"th06 16bits mode",
		"th06 accept",
		"th06 cancel",
		"th06 screen mode",
		"th06 refresh rate",
		"th06 colors",
		null,
		null,
		"th06 pad X axis",
		"th06 pad Y axis",
		"th06 check pad",
		null,
		"th06 DirectInput"
	]
}
