{
	"th01": "Touhou Rei'iden - Highly Responsive to Prayers",
	"th02": "Touhou Fuumaroku - The Story of Eastern Wonderland",
	"th03": "Touhou Yumejikuu - Phantasmagoria of Dim. Dream",
	"th04": "Touhou Gensokyo - Lotus Land Story",
	"th05": "Touhou Kaikidan - Mystic Square",
	"th06": "Touhou Koumakyou - The Embodiment of Scarlet Devil",
	"th07": "Touhou Youyoumu - Perfect Cherry Blossom",
	"th08": "Touhou Eiyashou - Imperishable Night",
	"th09": "Touhou Kaeidzuka - Phantasmagoria of Flower View",
	"th095": "Touhou Bunkachou - Shoot the Bullet",
	"th10": "Touhou Fuujinroku - Mountain of Faith",
	"alcostg": "Tasogare Sakaba - Uwabami Breakers",
	"th11": "Touhou Chireiden - Subterranean Animism",
	"th12": "Touhou Seirensen - Undefined Fantastic Object",
	"th125": "Double Spoiler - Touhou Bunkachou",
	"th128": "Yousei Daisensou - Touhou Sangetsusei",
	"th13": "Touhou Shinreibyou - Ten Desires",
	"th14": "Touhou Kishinjou - Double Dealing Character",
	"th10 JP": "Touhou Fuujinroku",
	"alcostg JP": "Tasogare Sakaba",
	"th11 JP": "Touhou Chireiden",
	"th12 JP": "Touhou Seirensen",
	"th125 JP": "Double Spoiler",
	"th128 JP": "Yousei Daisensou",
	"th13 JP": "Touhou Shinreibyou",
	"th14 JP": "Touhou Kishinjou",
	"th13 Spell Practice Unknown": " No.%3d  ???????????",
	"th10 Result Unknown Spell": "No. <r$%3d$999>  ????????????????????? <r$%4d/%4d$>",
	"Music Room Unknown Title": "No. <r$%2d$99>  ???????????"
}
