{
	"th01": "Touhou Rei'iden - Highly Responsive to Prayers",
	"th02": "Touhou Fuumaroku - The Story of Eastern Wonderland",
	"th03": "Touhou Yumejikuu - Phantasmagoria of Dim. Dream",
	"th04": "Touhou Gensoukyou - Lotus Land Story",
	"th05": "Touhou Kaikidan - Mystic Square",
	"th06": "Touhou Koumakyou - The Embodiment of Scarlet Devil",
	"th07": "Touhou Youyoumu - Perfect Cherry Blossom",
	"th08": "Touhou Eiyashou - Imperishable Night",
	"th09": "Touhou Kaeidzuka - Phantasmagoria of Flower View",
	"th095": "Touhou Bunkachou - Shoot the Bullet",
	"th10": "Touhou Fuujinroku - Mountain of Faith",
	"alcostg": "Tasogare Sakaba - Uwabami Breakers",
	"th11": "Touhou Chireiden - Subterranean Animism",
	"th12": "Touhou Seirensen - Undefined Fantastic Object",
	"th125": "Double Spoiler - Touhou Bunkachou",
	"th128": "Yousei Daisensou - Touhou Sangetsusei",
	"th13": "Touhou Shinreibyou - Ten Desires",
	"th14": "Touhou Kishinjou - Double Dealing Character",
	"th143": "Danmaku Amanojaku - Impossible Spell Card",
	"th15": "Touhou Kanjuden - Legacy of Lunatic Kingdom",
	"th16": "Touhou Tenkuushou - Hidden Star in Four Seasons",
	"th165": "Hifuu Nightmare Diary - Violet Detector",
	"th17": "Touhou Kikeijuu - Wily Beast and Weakest Creature",
	"th18": "Touhou Kouryuudou - Unconnected Marketeers",
	"th185": "Bulletphilia-tachi no Yamiichiba ~ 100th Black Market",
	"th19": "Touhou Juuouen ~ Unfinished Dream of All Living Ghost",
	"th20": "Touhou Kinjoukyou ~ Fossilized Wonders",
	"th10 JP": "Touhou Fuujinroku",
	"alcostg JP": "Tasogare Sakaba",
	"th11 JP": "Touhou Chireiden",
	"th12 JP": "Touhou Seirensen",
	"th125 JP": "Double Spoiler",
	"th128 JP": "Yousei Daisensou",
	"th13 JP": "Touhou Shinreibyou",
	"th14 JP": "Touhou Kishinjou",
	"th143 JP": "Danmaku Amanojaku",
	"th15 JP": "Touhou Kanjuden",
	"th16 JP": "Touhou Tenkuushou",
	"th165 JP": "Hifuu Nightmare Diary",
	"th17 JP": "Touhou Kikeijuu",
	"th18 JP": "Touhou Kouryuudou",
	"th185 JP": "Bulletphilia-tachi no Yamiichiba",
	"th19 JP": "Touhou Juuouen",
	"th20 JP": "Touhou Kinjoukyou",
	"th13 Spell Practice Unknown": "Â No.%3d  ???????????",
	"th10 Result Unknown Spell": "No. <r$%3d$999>  ????????????????????? <r$%4d/%4d$>",
	"th15 Result Known Spell": "No. <r$%s%s%s$999>  %s <r$%4d/%4d$>",
	"th15 Result Unknown Spell": "No. <r$%s%s%s$999>  ????????????????????? <r$%4d/%4d$>",
	"Music Room Unknown Title": "No. <r$%2d$99>  ???????????",
	"th143 Trophy Unknown": "????????????",
	"th15 Full-width 0": "0",
	"th15 Full-width 1": "1",
	"th15 Full-width 2": "2",
	"th15 Full-width 3": "3",
	"th15 Full-width 4": "4",
	"th15 Full-width 5": "5",
	"th15 Full-width 6": "6",
	"th15 Full-width 7": "7",
	"th15 Full-width 8": "8",
	"th15 Full-width 9": "9",
	"th20 Result Known Spell": "No.<r$%s%s%s$999>  %s",
	"th20 Result Unknown Spell": "No.<r$%s%s%s$999>  ?????????????????????",
	"th20 Full-width Space": " ",
	"th20 charname Reimu Hakurei full": "Hakurei Reimu",
    "th20 charname Marisa Kirisame full": "Kirisame Marisa",
	"th20 notice Reimu extra unlock": "Reimu %s",
	"th20 notice Marisa extra unlock": "Marisa %s",
	"th185 titlemsg charname format": "%s    %s    %s",
	"th08 Stats Reimu & Yukari": "Reimu & Yukari",
        "th08 Stats Marisa & Alice": "Marisa & Alice",
        "th08 Stats Sakuya & Remilia": "Sakuya & Remilia",
        "th08 Stats Youmu & Yuyuko": "Youmu & Yuyuko",
        "th08 Stats Alice": "Alice Margatroid",
        "th08 Stats Remilia": "Remilia Scarlet"
}
